### ISSUE TITLE
support Go 1.13 Go Modules feature and parse MKV

### ISSUE THREAD

**Issue by tonytony2020** [ebml-go/webm#1]
hi, @xlab 

I found some issues on development

1. this package should support Go 1.13 Go Modules feature, issue `go mod init` on source root folder
2. run test will fail `go test ./... -mod=mod`
3. webm is based on MKV, a small patch make it parses MKV well

If I submit a PR for solve these issues would you like to merge it?

**Comment by xlab** [comment]
Of course! Thanks
